m10/m10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("quote_site/", include("quote_site.urls")),
    path("users/", include("users.urls"))
]

m10/quote_site/urls.py
from . import views
from django.urls import path

app_name = 'quote_site'
urlpatterns = [
    path("", views.index, name="index"),
    path('<int:id>/', views.author_detail, name='author_detail'),
    path('add_author', views.add_author, name="add_author"),
    path('add_quote', views.add_quote, name="add_quote")
]

m10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

m10/quote_site/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=200, null=False, unique=True)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=200, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField(null=False)
    tags = models.ManyToManyField(Tag, related_name='quotes')

    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="quotes")
    
    def __str__(self):
        return f"{self.author.fullname}: '{self.text[:30]}...'"

m10/quote_site/forms.py
from django import forms 

from .models import Author, Quote, Tag

class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    born_date = forms.DateField(widget=forms.DateInput(attrs={"class": "form-control", "placeholder": "DD/MM/YYYY"}))
    born_location = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    text = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    author = forms.ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=forms.Select(attrs={"class": "form-select"}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), widget=forms.SelectMultiple(attrs={"class": "form-select", "size": "7"}))

    class Meta:
        model = Quote
        fields = ['text', 'author', 'tags']

m10/quote_site/views.py
import json

from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


from .forms import AuthorForm, QuoteForm
from .models import Quote, Tag, Author


# Create your views here.
def get_top10tags():
    tags = Tag.objects.all()
    topTenTags: list = sorted(tags, key=lambda tag: (tag.quotes.all().count(), tag.name), reverse=True)[:10]
    return topTenTags

 
def index(request):
    quotes = Quote.objects.all().order_by("-id")
    topTenTags = get_top10tags()

    tag_name = request.GET.get('tag_name')
    if tag_name:
        try:
            tag_id = Tag.objects.get(name=tag_name.capitalize()).id
            quotes = quotes.filter(tags__in=[tag_id])    
        except Tag.DoesNotExist as e:
            quotes = []

    paginator = Paginator(quotes, 4)
    page = request.GET.get('page')
    quotes = paginator.get_page(page)

    return render(request, "quote_site/index.html", {"quotes": quotes, "topTenTags": topTenTags})

def author_detail(request, id):
    author = Author.objects.get(pk=id)

    return render(request, "quote_site/author_detail.html", {"author": author})

@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quote_site:index')

        return render(request, 'quote_site/add_author.html', {'form': form})

    return render(request, "quote_site/add_author.html", {'form': AuthorForm()})

@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quote_site:index')

        return render(request, 'quote_site/add_quote.html', {'form': form})

    return render(request, "quote_site/add_quote.html", {'form': QuoteForm()})

m10/quote_site/templates/quote_site/add_author.html
{% extends 'quote_site/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="offset-2 col-md-8">
                <br>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label"><h3>Fullname:</h3></label>
                        {{ form.fullname }}
                        <span>{{ form.errors.fullname }}</span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><h3>Born Date:</h3></label>
                        {{ form.born_date }}
                        <span>{{ form.errors.born_date }}</span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><h3>Born Location:</h3></label>
                        {{ form.born_location }}
                        <span>{{ form.errors.born_location }}</span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><h3>Biography:</h3></label>
                        {{ form.description }}
                        <span>{{ form.errors.description }}</span>
                    </div>

                    <button type="submit" class="btn btn-success btn-lg">Submit</button>
                    <button type="reset" class="btn btn-secondary btn-lg">Reset</button>
                </form>
            </div>
        </div>
    </div>


   
{% endblock body %}

m10/quote_site/templates/quote_site/add_quote.html
{% extends 'quote_site/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="offset-2 col-md-8">
                <br>
                <form method="POST">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label class="form-label"><h3>Quote Text:</h3></label>
                        {{ form.text }}
                        <span>{{ form.errors.text }}</span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><h3>Author:</h3></label>
                        {{ form.author }}
                        <span>{{ form.errors.author }}</span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><h3>Select tags:</h3></label>
                        {{ form.tags }}
                        <span>{{ form.errors.tags }}</span>
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    <button type="reset" class="btn btn-secondary btn-lg">Reset</button>

                </form>

            </div>
        </div>
    </div>


   
{% endblock body %}

m10/quote_site/templates/quote_site/author_detail.html
{% extends 'quote_site/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <br>
                <div class="card">
                    <div class="card-body">
                      <h1 class="card-title">{{ author.fullname }}</h1>
                      <hr>
                      <h5 class="card-subtitle mb-2 text-muted">Born: {{ author.born_date}} {{ author.born_location}}</h5>
                      <hr>
                      <p class="card-text"><h5>Biography:</h5> {{ author.description}} </p>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    

{% endblock body %}

m10/quote_site/templates/quote_site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'quote_site/style.css' %}">
    <title>Quote Site</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid ">
      <a class="navbar-brand" href="{% url 'quote_site:index' %}"><img src="https://cdn-icons-png.flaticon.com/512/9285/9285023.png" alt="Logo" width="50" height="40" class="d-inline-block align-text-top"></a>
      
      <div class="collapse navbar-collapse nav justify-content-between" id="navbarSupportedContent">
        <ul class="nav justify-content-between">
          <li class="nav-item">
            <a class="nav-link active btn btn-primary" aria-current="page" href="{% url 'quote_site:add_author' %}">Add Author</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active btn btn-warning" href="{% url 'quote_site:add_quote' %}">Add Quote</a>
          </li>
        </ul>
        <div>
        {% if user.is_authenticated %}
          <a class="nav-link active btn btn-success btn-sm link-light" href="{% url 'users:logout' %}">Logout</a>
        {% else %}
          <ul class="nav justify-content-between">
            <li class="nav-item">
              <a class="nav-link active btn btn-success btn-sm link-light" href="{% url 'users:register' %}">Create Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active btn btn-success btn-sm link-light" href="{% url 'users:login' %}">Login</a>
            </li>
          </ul>
        {% endif %}
        </div>
      </div>
    </div>
  </nav>
    {% block body %}
    {% endblock body %}
</body>
</html>

m10/quote_site/templates/quote_site/index.html
{% extends 'quote_site/base.html' %}

{% block body %}

<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col">
                        <input type="search" name="tag_name" placeholder="Search for tag" class="form-control form-control">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-warning" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-10">
            {% for quote in quotes %}
                {% include "quote_site/includes/quote.html" %}
            {% endfor %}
        </div>
        
        <div class="col-md-2">
            {% include "quote_site/includes/top_tags.html" %}
        </div>
    </div>
</div>

<div class="row d-flex align-items-center">
    <div class="col-md-4 offset-md-4">
        <ul class="pagination">
            {% if quotes.has_previous %}
                <li class="page-item">
                    <a class="page-link page-link-warning" href="?page={{ quotes.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            
            <li class="page-item active">
                <a class="page-link" href="?page={{ quotes.number }}">Current</a>
            </li>

                
            {% if quotes.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotes.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

{% endblock body %}