m10/m10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("quote_site/", include("quote_site.urls")),
    path("users/", include("users.urls"))
]

m10/quote_site/urls.py
from . import views
from django.urls import path

app_name = 'quote_site'
urlpatterns = [
    path("", views.index, name="index"),
    path('<int:id>/', views.author_detail, name='author_detail'),
    path('add_author', views.add_author, name="add_author"),
    path('add_quote', views.add_quote, name="add_quote")
]

m10/quote_site/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=200, null=False, unique=True)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=200, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField(null=False)
    tags = models.ManyToManyField(Tag, related_name='quotes')

    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="quotes")
    
    def __str__(self):
        return f"{self.author.fullname}: '{self.text[:30]}...'"

m10/quote_site/forms.py
from django import forms 

from .models import Author, Quote, Tag

class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    born_date = forms.DateField(widget=forms.DateInput(attrs={"class": "form-control", "placeholder": "DD/MM/YYYY"}))
    born_location = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    text = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    author = forms.ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=forms.Select(attrs={"class": "form-select"}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), widget=forms.SelectMultiple(attrs={"class": "form-select", "size": "7"}))

    class Meta:
        model = Quote
        fields = ['text', 'author', 'tags']

m10/quote_site/views.py
import json

from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


from .forms import AuthorForm, QuoteForm
from .models import Quote, Tag, Author


# Create your views here.
def get_top10tags():
    tags = Tag.objects.all()
    topTenTags: list = sorted(tags, key=lambda tag: (tag.quotes.all().count(), tag.name), reverse=True)[:10]
    return topTenTags

 
def index(request):
    quotes = Quote.objects.all().order_by("-id")
    topTenTags = get_top10tags()

    tag_name = request.GET.get('tag_name')
    if tag_name:
        try:
            tag_id = Tag.objects.get(name=tag_name.capitalize()).id
            quotes = quotes.filter(tags__in=[tag_id])    
        except Tag.DoesNotExist as e:
            quotes = []

    paginator = Paginator(quotes, 4)
    page = request.GET.get('page')
    quotes = paginator.get_page(page)

    return render(request, "quote_site/index.html", {"quotes": quotes, "topTenTags": topTenTags})

def author_detail(request, id):
    author = Author.objects.get(pk=id)

    return render(request, "quote_site/author_detail.html", {"author": author})

@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quote_site:index')

        return render(request, 'quote_site/add_author.html', {'form': form})

    return render(request, "quote_site/add_author.html", {'form': AuthorForm()})

@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quote_site:index')

        return render(request, 'quote_site/add_quote.html', {'form': form})

    return render(request, "quote_site/add_quote.html", {'form': QuoteForm()})

m10/quote_site/templates/quote_site/includes/quote.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
{% block body %}
    <figure class="bg-light p-4" style="border-left: .35rem solid #fcdb5e; border-top: 1px solid #eee; border-right: 1px solid #eee; border-bottom: 1px solid #eee;">
        <i class="fas fa-quote-left fa-2x mb-4" style="color: #fcdb5e;"></i>
        <blockquote class="blockquote pb-2">
            <p>"{{ quote.text }}"</p>
        </blockquote>
        <figcaption class="blockquote-footer mb-0">
            <h5> By <cite><a href="{% url 'quote_site:author_detail' quote.author.id %}" class="link-info">{{ quote.author.fullname }}</a></cite></h5>
        </figcaption>
        <br>
        <h5>Tags: 
            {% for tag in quote.tags.all %}
                <a type="submit" class="btn btn-primary btn-sm" name="tag_name" href="?tag_name={{ tag.name }}">{{ tag }}</a>
            {% endfor %}
        </h5>
    </figure>
    <br>


  
{% endblock body %}

m10/quote_site/templates/quote_site/includes/top_tags.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
{% block body %}
<div class="card" >
    <div class="card-header" style="text-align: center;">
      <h3>Top 10 tags</h3>
    </div>
    <ul class="list-group list-group-flush" style="text-align: center;">
        {% for tag in topTenTags %}
            <li class="list-group-item"><a type="submit" class="btn btn-success btn-sm" name="tag_name" href="?tag_name={{ tag.name }}">{{ tag }}</a></li>
        {% endfor %}
    </ul>
  </div>

{% endblock body%}