m10/m10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("quote_site/", include("quote_site.urls")),
    path("users/", include("users.urls"))
]

m10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

m10/users/models.py
from django.db import models

# Create your models here.

m10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    password1 = forms.CharField(max_length=50,  required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=50,  required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']

m10/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm
# Create your views here.

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def dispatch(self, request,  *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quote_site:index")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            # username = form.cleaned_data["username"]
            messages.success(request, f"Your account was successfully created!")
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": self.form_class()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('users:logout')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quote_site:index')

    return render(request, 'users/login.html', context={"form": LoginForm()})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

m10/users/templates/users/login.html
{% extends 'quote_site/base.html' %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ form.non_field_errors }}</span>
    </div>
{% endif %} 

{% block body %}
    <div class="container">
        <div class="row">
            <div class="offset-4 col-md-4">
                <form method="post" action="{% url 'users:login' %}">
                    {% csrf_token %}
                    <br>
                    <div>
                        <label> <h3>Username:</h3></label>
                            {{ form.username }}
                        <span>{{ form.errors.username }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password:</h3> </label>
                            {{ form.password }}
                        <span>{{ form.errors.password }}</span>
                    </div>
                    <br>
                    <div class="grid d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Log In</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                    <div class="small text-center ">
                        <a href="{% url "users:password_reset" %}" class="text-center text-primary"><i>Forgot Password?</i></a>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
{% endblock body %}

m10/users/templates/users/logout.html
{% extends 'quote_site/base.html' %}

{% block body %}
    <br>
    <h1 style="text-align: center;">BYE!</h1>
{% endblock body %}

m10/users/templates/users/password_reset.html
{% extends "quote_site/base.html" %}

{% block body %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock body %}

m10/users/templates/users/password_reset_complete.html
{% extends "quote_site/base.html" %}

{% block body %}

    <h2>Password reset complete!</h2>

{% endblock %}

m10/users/templates/users/password_reset_confirm.html
{% extends "quote_site/base.html" %}

{% block body %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

m10/users/templates/users/password_reset_done.html
{% extends "quote_site/base.html" %}

{% block body %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

m10/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

m10/users/templates/users/register.html
{% extends 'quote_site/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="offset-4 col-md-4">
                <form method="POST">
                    {% csrf_token %}
                    <br>
                    <div>
                        <label> <h3>Username:</h3></label>
                            {{ form.username }}
                        <span>{{ form.errors.username }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Email:</h3></label>
                            {{ form.email }}
                        <span>{{ form.errors.email }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password:</h3> </label>
                            {{ form.password1 }}
                        <span>{{ form.errors.password1 }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password confirmation:</h3></label>
                            {{ form.password2 }}
                        <span>{{ form.errors.password2 }}</span>
                    </div>
                    <br>

                    <div class="grid d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock body %}